# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  commands:
    - git fetch --unshallow --tags || (git fetch --depth=50 && git fetch --tags)

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs


sphinx:
  configuration: docs/conf.py
