language: python

os:
  - linux

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy
      - python-setuptools

install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install -e .

script:
  py.test --cov=formulate --verbose --run-slow

after_success:
  coveralls

notifications:

deploy:
  provider: pypi
  user: chrisburr
  password:
    secure: iyObYOZyVhK6jDy4NpLHwWZdlq5USPy4EgFcsKN+uSH8KfihDskdxcYXCbP/k692fjtZO6oIwLaia3HQc0NIl48Yh7Z4uvo3k+hVZQ5YnQTXyMtksYb3jQWvAwbEfG6gahy3xuG3Fcu/XoOyyJ6iDsfsCH1DsrL7TRNBby4T/jXipyy9FE2cEq6MSsPJz3dXmJVR+O4vIZNXj3BSk+yg/Zmn1q62A33I2QJ3wqpuK9XusN1KntwdKbH/FR0dZVMct76zNpb1YPk7Vm2/CNCM26djDtERLAoOSBoXxPcDbRNwe6zSSAGg/o6MwSLbg61os1SfmQhzcoDR8G9wcDRM/WExC0TWSd99J55j31IqiDfy7x7gTOiikPHdlxbKlURNScGWvxLP5VwDWEoml0ibLqS7L14lHQYkuHswdGJ02tBlWvTqDGttVIBp3ydyNPof/Vv06K7MTXdt3+zOVrObLzIK5+tBWcKU5Vb6e0sivtFf1/foBrWBPAhpB8zCEMu/K54gbauR/oSL5RGl96rrwRZJXvzk4HIWSnufkk5xsbfUJ5sCZghF0hwyr8L+Iu6351aH0cpdEmfUZxo3RLURCCx4ZG8LA3Nn8YFB6m3tNEpfpGImz+kqsonziUJo46SHIlwPIXJdCY73UmAuQfHcF4IIoC9WO9bFl1+AlUdVAa4=
  on:
    tags: true
    branch: master
