language: python

os:
  - linux

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy
      - python-setuptools

install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install pytest

script:
  coverage run --source=formulate setup.py test

after_success:
  coveralls

notifications:
