name: CD

on:
  release:
    types:
      - published
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - "ci/*"
  pull_request:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -e ".[docs]"

      - name: Build documentation
        run: |
          cd docs
          make html -j 4

  deploy:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [ dist ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/formulate
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*"

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
