name: unittests

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - "ci/*"
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash -l {0}"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    name: Tests for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          environment-name: formulate-env
          create-args: >-
            --strict-channel-priority
            conda-forge/label/python_rc::_python_rc
            python=${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          conda install coveralls uv pytest-cov root -y
          uv pip install --system .[dev,test]

      - name: Test with pytest
        run: |
          pytest --cov=formulate --verbose
