name: unittests

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
      - "ci/*"
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash -l {0}"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    name: Tests for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          activate-environment: formulate-env

      # - name: Install ROOT
      #   run: |
      #     mamba install root -y

      - name: Install test dependencies
        run: |
          mamba install coveralls uv pytest-cov root -y
          uv pip install --system .[dev,test]

      - name: Test with pytest
        run: |
          pytest --cov=formulate --verbose
